# -*- coding: utf-8 -*-
"""lab 1 carla Sofia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jp8bkjJwn2WMWdQTaZ03z6TuBFdoAdh-
"""

from google.colab import files
uploaded = files.upload()

"""Dados de Treino"""

import pandas as pd
import pickle as p1
from sklearn import linear_model
import numpy as np

# Carregar o dataset localmente
data = pd.read_csv("digits.csv", sep=";")

# Verificar a estrutura do dataset
print("Colunas disponíveis:", data.columns.tolist())
print("Shape do dataset:", data.shape)

# Assumindo que a última coluna é o target
X = data.iloc[:, :-1].values  # features
y = data.iloc[:, -1].values   # target

# Número total de dados
M = len(data)
print("Nº total de dados:", M)

# Número de parâmetros (features)
n_parametros = X.shape[1]
print("Nº total de parâmetros:", n_parametros, "+ 1")

# Definir tamanho do treino (2/3 dos dados)
m = int(2 * M / 3)
print("Nº total de dados de treino:", m)

# Separar dados de treino
train_X = X[:m]
train_y = y[:m]

# Dados de teste
teste_X = X[m:]
teste_y = y[m:]

# Salvar dados de teste
Dadosteste = [teste_X, teste_y]
with open("Dadosteste.pkl", "wb") as Dt:
    p1.dump(Dadosteste, Dt)

# Criar e treinar o modelo
regr = linear_model.LinearRegression()
Modelo = regr.fit(train_X, train_y)

# Guardar o modelo
with open('digits_predictor', 'wb') as PickleModelo:
    p1.dump(Modelo, PickleModelo)

print("Modelo guardado com sucesso!")
print("Dimensão do modelo: ", Modelo.coef_.shape)

"""Dados de Teste"""

# Teste



# Carregar dados de teste
with open("Dadosteste.pkl", "rb") as Dt:
    Dadosteste = p1.load(Dt)

data_X = Dadosteste[0]
data_Y = Dadosteste[1]

print("Tipo de data_X:", type(data_X))
print("Shape de data_X:", data_X.shape)
print("Shape de data_Y:", data_Y.shape)

# Carregar modelo
Modelogravado = p1.load(open('digits_predictor', 'rb'))
print("Coeficientes:\n", Modelogravado.coef_)

# Fazer predições
y_pred = Modelogravado.predict(data_X)

# Calcular erro (diferença entre predição e valor real)
z_pred = y_pred - data_Y

# Para classificação, precisamos arredondar as predições para o dígito mais próximo
# e limitar entre 0 e 9 (dígitos válidos)
y_pred_rounded = np.round(y_pred).astype(int)
y_pred_rounded = np.clip(y_pred_rounded, 0, 9)  # garantir que está entre 0 e 9

# Calcular acurácia
right = 0
wrong = 0
total = len(data_Y)

for i in range(total):
    if y_pred_rounded[i] == data_Y[i]:
        right += 1
    else:
        wrong += 1

print("Eficácia de acertos:", (right/total)*100)
print("Taxa de erro:", (wrong/total)*100)

# Alternativa mais eficiente usando NumPy
accuracy = np.mean(y_pred_rounded == data_Y)
print("\nAcurácia (método NumPy):", accuracy)

# Métricas adicionais
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(data_Y, y_pred)
r2 = r2_score(data_Y, y_pred)

print("\nMSE (Erro Quadrático Médio):", mse)
print("R² Score:", r2)

"""Dados de Previsão"""

import pandas as pd
import pickle as p1
from sklearn import linear_model
#import numpy as np

dados_importar = "0;0;5;13;9;1;0;0;0;0;13;15;10;15;5;0;0;3;15;2;0;11;8;0;0;4;12;0;0;8;8;0;0;5;8;0;0;9;8;0;0;4;11;0;1;12;7;0;0;2;14;5;10;12;0;0;0;0;6;13;10;0;0;0"
dados_importar =dados_importar.replace(";", " ")

try:
    entrada = dados_importar
    data_x = list(map(float, entrada.split()))

    if len(data_x) == n_parametros:
        data_x_pd = pd.DataFrame([data_x])
        y_pred_manual = Modelogravado.predict(data_x_pd)
        print(f"\nPrevisão: {int(np.round(y_pred_manual[0]))}")
    else:
        print(f"Erro: Esperados {n_parametros} valores, recebidos {len(data_x)}")
except Exception as e2:
    print(f"Erro na entrada manual: {e2}")