# -*- coding: utf-8 -*-
"""Lab1_AA_CarlaSofia_Gomes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0Kyt-0a38qVWwnMcRFwGGs3DOvhIP1a
"""

import matplotlib.pyplot as plt
import pickle as p1
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

from google.colab import files #Importa o módulo "files" da biblioteca google.colab
uploaded = files.upload()

data = pd.read_csv("winequality-white.csv", sep=";")

print(data.head(5))

"""**Dados de Treino** - 1000 linhas (2/3) dos dados"""

train_data=data[:1000]
data_X=train_data.iloc[:,0:11]
data_Y=train_data.iloc[:,11:12]
#print(train_data.columns)
print(data_X)
print(data_Y)
regr = linear_model.LinearRegression()
preditor_linear_model=regr.fit(data_X, data_Y)
preditor_Pickle = open('white-wine_quality_predictor', 'wb')
print("white-wine_quality_predictor")
p1.dump(preditor_linear_model, preditor_Pickle)

"""**Dados de Teste**"""

# Linha 1: CORRETA (mas tem gap)
evaluation_data = data[1000:]  # Funciona, mas pula a linha 1000

# Linha 2: CORRETA
data_X = evaluation_data.iloc[:, 0:11]  # Seleciona primeiras 11 colunas

# Linha 3: CORRETA
data_Y = evaluation_data.iloc[:, 11:12]  # Seleciona coluna 12 como DataFrame

# Linha 4: CORRETA
print(type(evaluation_data))  # Mostra o tipo

# Linha 5: CORRETA
print(type(data_X))  # Mostra o tipo

loaded_model = p1.load(open('white-wine_quality_predictor', 'rb'))

# Linha 7: PROBLEMA DE DIGITAÇÃO - "Coefficientes" (português) vs "Coefficients" (inglês)
print("Coeficientes: \n", loaded_model.coef_)  # Funciona, mas texto estranho

# Linha 8: CORRETA
y_pred = loaded_model.predict(data_X)

# Linha 9: PROBLEMA - shape incompatível
z_pred = y_pred - data_Y  # PODE DAR ERRO!

"""**Nível de Precisão**

"""

from sklearn.metrics import accuracy_score, mean_absolute_error

# Converter predições
y_pred_int = np.round(y_pred).astype(int).flatten()
y_true = data_Y.values.flatten().astype(int)

# Calcular acertos
right = np.sum(y_pred_int == y_true)
wrong = np.sum(y_pred_int != y_true)
total = len(y_true)

# Métricas
accuracy = (right / total) * 100
mae = mean_absolute_error(y_true, y_pred_int)

print(f"Total de amostras: {total}")
print(f"Acertos: {right} ({accuracy:.2f}%)")
print(f"Erros: {wrong} ({100-accuracy:.2f}%)")
print(f"Erro Médio Absoluto (MAE): {mae:.2f}")

"""**Previsões em Pontos Desconhecidos**"""

data_x=float(input("introduza valores do wine\n"))
data=data_x.split(";")
print(data)
fmap_data = map(float, data)
print(fmap_data)
flist_data = list(fmap_data)
print(flist_data)
data1 = pd.read_csv("winequality-white.csv",sep=";")
data2=data1.iloc[:0,:11]
data_preparation=pd.DataFrame([flist_data],columns=list(data2))
out=data2
for x in out:
  print(x,data_preparation[x].values)
loaded_model = p1.load(open('../white-wine_quality_predictor', 'rb'))
y_pred=loaded_model.predict(data_preparation)
print("wine quality",int(y_pred))